In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/extracted/profiles_full.csv')

### making profiles_full lighter demographics-only for tableau demographics dashboard to use

In [4]:
demographics_df = df[['age','gender','orientation','desires','interests']]

In [5]:
demographics_df.head()

,age,gender,orientation,desires,interests
0,25,woman,pansexual,"['kink', 'bdsm', 'kinbaku', 'sensual', 'dates'...","['reading', 'science', 'hiking']"
1,41,man,bisexual,"['singles', 'friendships', 'dates']","['faith', 'music', 'rollerblading', 'art']"
2,32,man,gay,"['threeway', 'kink', 'friendships', 'casual', ...","['hiking', 'travel', 'concerts', 'beach', 'pla..."
3,26,woman,bi-curious,"['dominant', 'sensual', 'foreplay', 'dates', '...","['traveling', 'tequila', 'languages', 'f1', 'l..."
4,34,woman,bisexual,"['submissive', 'casual', 'sensual', 'friendshi...","['hiking', 'pole dance', 'fantasy/sci fi', 'ki..."

In [6]:
demographics_df.to_csv('data/extracted/profiles_full.csv',index=False)

### splitting desires and interests dataframes

In [8]:
df = df.drop(columns=['desires','interests','age'], index=1)

In [9]:
df.head()

,gender,orientation,desire: dates,desire: singles,desire: casual,desire: sensual,desire: kink,desire: friendships,desire: foreplay,desire: dominant,...,interest: aerial dance,interest: aerial,interest: activist,interest: activism,interest: active,interest: acting,interest: acro yoga,interest: abolition,interest: a perfect taco,interest: 4/20
0,woman,pansexual,1,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,man,gay,0,0,1,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,woman,bi-curious,1,0,0,1,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
4,woman,bisexual,0,0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
5,woman,polysexual,1,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
desires_df = df.drop(df.columns[351:],axis=1)
desires_df

,gender,orientation,desire: dates,desire: singles,desire: casual,desire: sensual,desire: kink,desire: friendships,desire: foreplay,desire: dominant,...,desire: bicurious,desire: bi,desire: being spoiled,desire: being spanked,desire: behavior moding,desire: banter,desire: automated,desire: assistant,desire: ask,desire: 420
0,woman,pansexual,1,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,man,gay,0,0,1,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,woman,bi-curious,1,0,0,1,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
4,woman,bisexual,0,0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
5,woman,polysexual,1,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,woman,bisexual,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
331,woman,straight,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
332,woman,bisexual,1,1,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
333,woman,bisexual,0,1,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
334,woman,bisexual,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
interests_df = df.drop(df.columns[2:351],axis=1)
interests_df

,gender,orientation,interest: travel,interest: music,interest: art,interest: reading,interest: cooking,interest: dancing,interest: movies,interest: museums,...,interest: aerial dance,interest: aerial,interest: activist,interest: activism,interest: active,interest: acting,interest: acro yoga,interest: abolition,interest: a perfect taco,interest: 4/20
0,woman,pansexual,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,man,gay,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,woman,bi-curious,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,woman,bisexual,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,woman,polysexual,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,woman,bisexual,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
331,woman,straight,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
332,woman,bisexual,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
333,woman,bisexual,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
334,woman,bisexual,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### splitting dataframes into different demographics

In [13]:

straight_woman_desires_df = desires_df[(desires_df['gender']=='woman') & (desires_df['orientation']=='straight')]
straight_woman_interests_df = interests_df[(df['gender']=='woman') & (df['orientation']=='straight')]

bisexual_woman_desires_df = desires_df[(df['gender']=='woman') & (df['orientation']=='bisexual')]
bisexual_woman_interests_df = interests_df[(df['gender']=='woman') & (df['orientation']=='bisexual')]

queer_woman_desires_df = desires_df[(df['gender']=='woman') & (df['orientation']=='queer')]
queer_woman_interests_df = interests_df[(df['gender']=='woman') & (df['orientation']=='queer')]


gay_man_desires_df = desires_df[(df['gender']=='man') & (df['orientation']=='gay')]
gay_man_interests_df = interests_df[(df['gender']=='man') & (df['orientation']=='gay')]

bisexual_man_desires_df = desires_df[(df['gender']=='man') & (df['orientation']=='bisexual')]
bisexual_man_interests_df = interests_df[(df['gender']=='man') & (df['orientation']=='bisexual')]

queer_man_desires_df = desires_df[(df['gender']=='man') & (df['orientation']=='queer')]
queer_man_interests_df = interests_df[(df['gender']=='man') & (df['orientation']=='queer')]

**totals of men and women profiled**

In [14]:

print(len(straight_woman_desires_df) + len(bisexual_woman_desires_df) + len(queer_woman_desires_df))
print(len(gay_man_desires_df)+ len(bisexual_man_desires_df) + len(queer_man_desires_df))

152
45

### creating function to calculate top 5 desires and interests

In [16]:
def top(df):
    top_dict = {}
    counts = df.sum(numeric_only=True)
    names = counts.index
    totals = []
    for name,count in zip(names,counts):
        if 'desire:' in name:
            top_dict[name[8:]] = round(count/len(df),2)
        elif 'interest:' in name:
            top_dict[name[9:]] = round(count/len(df),2)
        totals.append(count)
    d_or_i = top_dict.keys()
    percents = top_dict.values()
    if 'desire:' in names[0]:
        results = pd.DataFrame({'desire':d_or_i,'percentage':percents, 'counts':totals})
    elif 'interest' in names[0]:
        results = pd.DataFrame({'interest':d_or_i,'percentage':percents, 'counts':totals})
    results = results.sort_values(by='percentage',ascending=False)
    return results[:5]

### applying function to different demographics

In [18]:
top_all_desires_df = top(desires_df)
top_all_desires_df

    desire  percentage  counts
0    dates        0.54     181
1  singles        0.49     162
2   casual        0.46     153
3  sensual        0.44     146
4     kink        0.38     127

In [19]:
top_all_interests_df = top(interests_df)
top_all_interests_df

   interest  percentage  counts
0    travel        0.22      74
2       art        0.19      64
1     music        0.19      65
3   reading        0.15      50
4   cooking        0.15      50

In [20]:

top_straight_woman_desires_df = top(straight_woman_desires_df)
top_straight_woman_interests_df = top(straight_woman_interests_df)

top_bisexual_woman_desires_df = top(bisexual_woman_desires_df)
top_bisexual_woman_interests_df = top(bisexual_woman_interests_df)

top_queer_woman_desires_df = top(queer_woman_desires_df)
top_queer_woman_interests_df = top(queer_woman_interests_df)



top_gay_man_desires_df = top(gay_man_desires_df)
top_gay_man_interests_df = top(gay_man_interests_df)

top_bisexual_man_desires_df = top(bisexual_man_desires_df)
top_bisexual_man_interests_df = top(bisexual_man_interests_df)

top_queer_man_desires_df = top(queer_man_desires_df)
top_queer_man_interests_df = top(queer_man_interests_df)

In [21]:

top_straight_woman_desires_df.to_csv('data/extracted/top_straight_woman_desires.csv',index=False)
top_straight_woman_interests_df.to_csv('data/extracted/top_straight_woman_interests.csv',index=False)

top_bisexual_woman_desires_df.to_csv('data/extracted/top_bisexual_woman_desires.csv',index=False)
top_bisexual_woman_interests_df.to_csv('data/extracted/top_bisexual_woman_interests.csv',index=False)

top_queer_woman_desires_df.to_csv('data/extracted/top_queer_woman_desires.csv',index=False)
top_queer_woman_interests_df.to_csv('data/extracted/top_queer_woman_interests.csv',index=False)



top_gay_man_desires_df.to_csv('data/extracted/top_gay_man_desires.csv',index=False)
top_gay_man_interests_df.to_csv('data/extracted/top_gay_man_interests.csv',index=False)

top_bisexual_man_desires_df.to_csv('data/extracted/top_bisexual_man_desires.csv',index=False)
top_bisexual_man_interests_df.to_csv('data/extracted/top_bisexual_man_interests.csv',index=False)

top_queer_man_desires_df.to_csv('data/extracted/top_queer_man_desires.csv',index=False)
top_queer_man_interests_df.to_csv('data/extracted/top_queer_man_interests.csv',index=False)